repos:
-   repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args:
          - --python-version=3.9
          - --warn-unused-configs
          - --ignore-missing-imports
          - --pretty
