name: Test and Lint
on: [push]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # Needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/ci.txt
      - name: Style checks
        run: flake8 .
      - name: Imports formatting checks
        run: isort . --check
      - name: Code formatting checks
        run: black . --check
      - name: Type checks
        run: mypy .
      - name: Tests
        run: py.test

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: [test-and-lint]
    if: github.ref == 'refs/heads/production'
    steps:
      # Build and deploy ...
      - run: echo "Faking build and deployment ..."
